//! The `apply_patch` parser + applier — a Rust port of opencode
//! `packages/opencode/src/patch/index.ts` (686 lines).
//!
//! The patch language is a stripped-down, file-oriented diff format wrapped in
//! `*** Begin Patch` / `*** End Patch` markers. This module implements the
//! parser ([`parse_patch`], `index.ts:185-241`), the per-chunk applier
//! ([`derive_new_contents_from_chunks`], `index.ts:307-340`) with its four-pass
//! fuzzy [`seek_sequence`] (`index.ts:460-484`), and a filesystem applier
//! ([`apply_hunks_to_files`], `index.ts:514-561`). BOM handling mirrors
//! `packages/opencode/src/util/bom.ts`.
//!
//! Unlike opencode's naive line-by-line `generateUnifiedDiff`
//! (`index.ts:486-511`), the unified diff here is produced with the `similar`
//! crate so update summaries are real diffs.

use std::path::{Path, PathBuf};

use regex::Regex;
use similar::TextDiff;

// ---- types (index.ts:19-46) -------------------------------------------------

/// A single file operation parsed from a patch (`Hunk`, `index.ts:19-22`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Hunk {
    /// `*** Add File:` — create a new file with `contents`.
    Add {
        /// Target path (relative to the patch cwd).
        path: String,
        /// Initial file contents (the joined `+` lines, no trailing newline).
        contents: String,
    },
    /// `*** Delete File:` — remove an existing file.
    Delete {
        /// Path to remove.
        path: String,
    },
    /// `*** Update File:` — patch a file in place (optionally renaming it).
    Update {
        /// Path to update.
        path: String,
        /// Optional `*** Move to:` rename target.
        move_path: Option<String>,
        /// The `@@`-delimited change chunks.
        chunks: Vec<UpdateFileChunk>,
    },
}

/// One `@@` chunk of an `*** Update File:` section (`index.ts:24-29`).
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct UpdateFileChunk {
    /// Lines expected in the original file (context + removed).
    pub old_lines: Vec<String>,
    /// Lines to write in their place (context + added).
    pub new_lines: Vec<String>,
    /// Optional `@@ <context>` anchor to seek before matching.
    pub change_context: Option<String>,
    /// Whether the chunk carried a `*** End of File` anchor.
    pub is_end_of_file: bool,
}

/// A resolved, per-path change ready to write (`ApplyPatchFileChange`,
/// `index.ts:37-40`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ApplyPatchFileChange {
    /// Create a file with `content`.
    Add {
        /// New file content.
        content: String,
    },
    /// Delete a file whose prior `content` was captured (for the diff).
    Delete {
        /// The content being removed.
        content: String,
    },
    /// Update a file, optionally moving it.
    Update {
        /// Unified diff (generated by `similar`).
        unified_diff: String,
        /// Optional rename target.
        move_path: Option<String>,
        /// The resulting file content.
        new_content: String,
    },
}

/// The set of paths touched by a patch application (`AffectedPaths`,
/// `index.ts:42-46`).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AffectedPaths {
    /// Files created.
    pub added: Vec<String>,
    /// Files updated or moved.
    pub modified: Vec<String>,
    /// Files deleted.
    pub deleted: Vec<String>,
}

/// The result of deriving new contents for an updated file (`index.ts:301-305`).
#[derive(Debug, Clone)]
pub struct FileUpdate {
    /// Unified diff between old and new content.
    pub unified_diff: String,
    /// Resulting file content (BOM stripped).
    pub content: String,
    /// Whether the original (or result) carried a UTF-8 BOM.
    pub bom: bool,
}

/// Errors surfaced by the parser/applier.
#[derive(Debug, thiserror::Error)]
pub enum PatchError {
    /// The Begin/End markers were missing or out of order (`index.ts:199`).
    #[error("Invalid patch format: missing Begin/End markers")]
    MissingMarkers,
    /// A chunk could not be located while applying (`index.ts:355`/`388`).
    #[error("{0}")]
    Apply(String),
    /// A filesystem operation failed.
    #[error("{0}")]
    Io(String),
}

// ---- BOM helpers (util/bom.ts:4-16) -----------------------------------------

const BOM: char = '\u{feff}';

/// Split a leading UTF-8 BOM off `text` (`bom.ts:7-10`).
pub(crate) fn bom_split(text: &str) -> (bool, &str) {
    if let Some(rest) = text.strip_prefix(BOM) {
        (true, rest)
    } else {
        (false, text)
    }
}

/// Re-attach a BOM to `text` when `bom` is set (`bom.ts:12-16`).
pub(crate) fn bom_join(text: &str, bom: bool) -> String {
    let (_, stripped) = bom_split(text);
    if bom {
        format!("{BOM}{stripped}")
    } else {
        stripped.to_string()
    }
}

// ---- heredoc unwrap (index.ts:176-183) --------------------------------------

/// Unwrap a `cat <<'EOF' … EOF` heredoc, returning the body (`index.ts:176-183`).
///
/// The `regex` crate lacks backreferences, so the closing delimiter is matched
/// manually rather than with the original `\1` pattern.
fn strip_heredoc(input: &str) -> String {
    let header = Regex::new(r#"(?s)^(?:cat\s+)?<<['"]?(\w+)['"]?[ \t]*\n(.*)$"#).unwrap();
    let Some(caps) = header.captures(input) else {
        return input.to_string();
    };
    let delim = caps.get(1).unwrap().as_str();
    let rest = caps.get(2).unwrap().as_str();
    let needle = format!("\n{delim}");
    let mut search_start = 0usize;
    while let Some(rel) = rest[search_start..].find(&needle) {
        let idx = search_start + rel;
        let after = idx + needle.len();
        if rest[after..].chars().all(char::is_whitespace) {
            return rest[..idx].to_string();
        }
        search_start = idx + 1;
    }
    input.to_string()
}

// ---- parser (index.ts:70-241) -----------------------------------------------

struct Header {
    file_path: String,
    move_path: Option<String>,
    next_idx: usize,
}

/// Parse an `*** Add/Delete/Update File:` header (`index.ts:70-101`).
fn parse_patch_header(lines: &[&str], start: usize) -> Option<Header> {
    let line = lines[start];
    if let Some(rest) = line.strip_prefix("*** Add File:") {
        let p = rest.trim();
        return (!p.is_empty()).then(|| Header {
            file_path: p.to_string(),
            move_path: None,
            next_idx: start + 1,
        });
    }
    if let Some(rest) = line.strip_prefix("*** Delete File:") {
        let p = rest.trim();
        return (!p.is_empty()).then(|| Header {
            file_path: p.to_string(),
            move_path: None,
            next_idx: start + 1,
        });
    }
    if let Some(rest) = line.strip_prefix("*** Update File:") {
        let p = rest.trim();
        if p.is_empty() {
            return None;
        }
        let mut move_path = None;
        let mut next_idx = start + 1;
        if next_idx < lines.len()
            && let Some(mv) = lines[next_idx].strip_prefix("*** Move to:")
        {
            move_path = Some(mv.trim().to_string());
            next_idx += 1;
        }
        return Some(Header {
            file_path: p.to_string(),
            move_path,
            next_idx,
        });
    }
    None
}

/// Parse the `@@`-delimited chunks of an update section (`index.ts:103-155`).
fn parse_update_file_chunks(lines: &[&str], start: usize) -> (Vec<UpdateFileChunk>, usize) {
    let mut chunks = Vec::new();
    let mut i = start;
    while i < lines.len() && !lines[i].starts_with("***") {
        if let Some(ctx) = lines[i].strip_prefix("@@") {
            let context_line = ctx.trim().to_string();
            i += 1;

            let mut old_lines = Vec::new();
            let mut new_lines = Vec::new();
            let mut is_end_of_file = false;

            // Note: opencode's inner-loop guard (`!startsWith("***")`) makes its
            // `*** End of File` branch dead code; we honor the documented intent
            // by consuming the marker before the `***` guard so `is_end_of_file`
            // (and the applier's EOF anchoring) actually functions.
            while i < lines.len() && !lines[i].starts_with("@@") {
                let change = lines[i];
                if change == "*** End of File" {
                    is_end_of_file = true;
                    i += 1;
                    break;
                }
                if change.starts_with("***") {
                    break;
                }
                if let Some(content) = change.strip_prefix(' ') {
                    old_lines.push(content.to_string());
                    new_lines.push(content.to_string());
                } else if let Some(content) = change.strip_prefix('-') {
                    old_lines.push(content.to_string());
                } else if let Some(content) = change.strip_prefix('+') {
                    new_lines.push(content.to_string());
                }
                i += 1;
            }

            chunks.push(UpdateFileChunk {
                old_lines,
                new_lines,
                change_context: (!context_line.is_empty()).then_some(context_line),
                is_end_of_file,
            });
        } else {
            i += 1;
        }
    }
    (chunks, i)
}

/// Parse the `+`-prefixed body of an `*** Add File:` section (`index.ts:157-174`).
fn parse_add_file_content(lines: &[&str], start: usize) -> (String, usize) {
    let mut content = String::new();
    let mut i = start;
    while i < lines.len() && !lines[i].starts_with("***") {
        if let Some(rest) = lines[i].strip_prefix('+') {
            content.push_str(rest);
            content.push('\n');
        }
        i += 1;
    }
    if content.ends_with('\n') {
        content.pop();
    }
    (content, i)
}

/// Parse a full patch into hunks (`index.ts:185-241`).
///
/// Strips a surrounding heredoc, requires the Begin/End markers, and walks each
/// file section. Returns [`PatchError::MissingMarkers`] when the envelope is
/// absent.
pub fn parse_patch(patch_text: &str) -> Result<Vec<Hunk>, PatchError> {
    let cleaned = strip_heredoc(patch_text.trim());
    let lines: Vec<&str> = cleaned.split('\n').collect();

    let begin_marker = "*** Begin Patch";
    let end_marker = "*** End Patch";
    let begin_idx = lines.iter().position(|l| l.trim() == begin_marker);
    let end_idx = lines.iter().position(|l| l.trim() == end_marker);

    let (begin_idx, end_idx) = match (begin_idx, end_idx) {
        (Some(b), Some(e)) if b < e => (b, e),
        _ => return Err(PatchError::MissingMarkers),
    };

    let mut hunks = Vec::new();
    let mut i = begin_idx + 1;
    while i < end_idx {
        let Some(header) = parse_patch_header(&lines, i) else {
            i += 1;
            continue;
        };
        if lines[i].starts_with("*** Add File:") {
            let (content, next_idx) = parse_add_file_content(&lines, header.next_idx);
            hunks.push(Hunk::Add {
                path: header.file_path,
                contents: content,
            });
            i = next_idx;
        } else if lines[i].starts_with("*** Delete File:") {
            hunks.push(Hunk::Delete {
                path: header.file_path,
            });
            i = header.next_idx;
        } else if lines[i].starts_with("*** Update File:") {
            let (chunks, next_idx) = parse_update_file_chunks(&lines, header.next_idx);
            hunks.push(Hunk::Update {
                path: header.file_path,
                move_path: header.move_path,
                chunks,
            });
            i = next_idx;
        } else {
            i += 1;
        }
    }
    Ok(hunks)
}

// ---- applier (index.ts:307-484) ---------------------------------------------

/// Derive new file contents by applying `chunks` to `original_text`
/// (`index.ts:307-340`).
pub fn derive_new_contents_from_chunks(
    file_path: &str,
    chunks: &[UpdateFileChunk],
    original_text: &str,
) -> Result<FileUpdate, PatchError> {
    let (orig_bom, original) = bom_split(original_text);

    let mut original_lines: Vec<String> = original.split('\n').map(str::to_string).collect();
    if original_lines.last().map(String::as_str) == Some("") {
        original_lines.pop();
    }

    let replacements = compute_replacements(&original_lines, file_path, chunks)?;
    let mut new_lines = apply_replacements(&original_lines, &replacements);

    if new_lines.last().map(String::as_str) != Some("") {
        new_lines.push(String::new());
    }

    let joined = new_lines.join("\n");
    let (next_bom, new_content) = bom_split(&joined);
    let new_content = new_content.to_string();

    let unified_diff = generate_unified_diff(original, &new_content);

    Ok(FileUpdate {
        unified_diff,
        content: new_content,
        bom: orig_bom || next_bom,
    })
}

type Replacement = (usize, usize, Vec<String>);

/// Compute `(start, old_len, new_lines)` replacements for each chunk
/// (`index.ts:342-396`).
fn compute_replacements(
    original_lines: &[String],
    file_path: &str,
    chunks: &[UpdateFileChunk],
) -> Result<Vec<Replacement>, PatchError> {
    let mut replacements: Vec<Replacement> = Vec::new();
    let mut line_index = 0usize;

    for chunk in chunks {
        if let Some(context) = &chunk.change_context {
            let ctx_pattern = [context.clone()];
            let context_idx = seek_sequence(original_lines, &ctx_pattern, line_index, false);
            let Some(context_idx) = context_idx else {
                return Err(PatchError::Apply(format!(
                    "Failed to find context '{context}' in {file_path}"
                )));
            };
            line_index = context_idx + 1;
        }

        // Pure addition (no old lines): insert before a trailing empty line.
        if chunk.old_lines.is_empty() {
            let insertion_idx = if original_lines.last().map(String::as_str) == Some("") {
                original_lines.len() - 1
            } else {
                original_lines.len()
            };
            replacements.push((insertion_idx, 0, chunk.new_lines.clone()));
            continue;
        }

        let mut pattern: Vec<String> = chunk.old_lines.clone();
        let mut new_slice: Vec<String> = chunk.new_lines.clone();
        let mut found = seek_sequence(original_lines, &pattern, line_index, chunk.is_end_of_file);

        // Retry without a trailing empty line if not found (index.ts:376-382).
        if found.is_none() && pattern.last().map(String::as_str) == Some("") {
            pattern.pop();
            if new_slice.last().map(String::as_str) == Some("") {
                new_slice.pop();
            }
            found = seek_sequence(original_lines, &pattern, line_index, chunk.is_end_of_file);
        }

        match found {
            Some(idx) => {
                replacements.push((idx, pattern.len(), new_slice));
                line_index = idx + pattern.len();
            }
            None => {
                return Err(PatchError::Apply(format!(
                    "Failed to find expected lines in {file_path}:\n{}",
                    chunk.old_lines.join("\n")
                )));
            }
        }
    }

    replacements.sort_by_key(|r| r.0);
    Ok(replacements)
}

/// Apply replacements in reverse order to avoid index shifting (`index.ts:398-415`).
fn apply_replacements(lines: &[String], replacements: &[Replacement]) -> Vec<String> {
    let mut result: Vec<String> = lines.to_vec();
    for (start_idx, old_len, new_segment) in replacements.iter().rev() {
        let end = (start_idx + old_len).min(result.len());
        result.splice(*start_idx..end, new_segment.iter().cloned());
    }
    result
}

/// Normalize Unicode punctuation to ASCII equivalents (`index.ts:417-425`).
fn normalize_unicode(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\u{2018}' | '\u{2019}' | '\u{201A}' | '\u{201B}' => out.push('\''),
            '\u{201C}' | '\u{201D}' | '\u{201E}' | '\u{201F}' => out.push('"'),
            '\u{2010}' | '\u{2011}' | '\u{2012}' | '\u{2013}' | '\u{2014}' | '\u{2015}' => {
                out.push('-');
            }
            '\u{2026}' => out.push_str("..."),
            '\u{00A0}' => out.push(' '),
            other => out.push(other),
        }
    }
    out
}

type Comparator = fn(&str, &str) -> bool;

/// Try to match `pattern` in `lines`, anchoring to EOF first when requested
/// (`index.ts:429-458`).
fn try_match(
    lines: &[String],
    pattern: &[String],
    start_index: usize,
    compare: Comparator,
    eof: bool,
) -> Option<usize> {
    if pattern.len() > lines.len() {
        return None;
    }
    if eof {
        let from_end = lines.len() - pattern.len();
        if from_end >= start_index
            && (0..pattern.len()).all(|j| compare(&lines[from_end + j], &pattern[j]))
        {
            return Some(from_end);
        }
    }
    for i in start_index..=(lines.len() - pattern.len()) {
        if (0..pattern.len()).all(|j| compare(&lines[i + j], &pattern[j])) {
            return Some(i);
        }
    }
    None
}

/// Four-pass fuzzy sequence search (`index.ts:460-484`): exact, rstrip, trim,
/// then Unicode-normalized comparison.
fn seek_sequence(
    lines: &[String],
    pattern: &[String],
    start_index: usize,
    eof: bool,
) -> Option<usize> {
    if pattern.is_empty() {
        return None;
    }
    let exact: Comparator = |a, b| a == b;
    let rstrip: Comparator = |a, b| a.trim_end() == b.trim_end();
    let trim: Comparator = |a, b| a.trim() == b.trim();
    let normalized: Comparator = |a, b| normalize_unicode(a.trim()) == normalize_unicode(b.trim());

    try_match(lines, pattern, start_index, exact, eof)
        .or_else(|| try_match(lines, pattern, start_index, rstrip, eof))
        .or_else(|| try_match(lines, pattern, start_index, trim, eof))
        .or_else(|| try_match(lines, pattern, start_index, normalized, eof))
}

/// Produce a unified diff via the `similar` crate (replaces the naive
/// `generateUnifiedDiff` at `index.ts:486-511`).
pub(crate) fn generate_unified_diff(old_content: &str, new_content: &str) -> String {
    if old_content == new_content {
        return String::new();
    }
    let diff = TextDiff::from_lines(old_content, new_content);
    let mut ud = diff.unified_diff();
    ud.context_radius(3);
    ud.to_string()
}

// ---- filesystem applier (index.ts:514-561) ----------------------------------

fn resolve(base: &Path, p: &str) -> PathBuf {
    let path = Path::new(p);
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        base.join(path)
    }
}

/// Apply hunks to the filesystem rooted at `base_dir` (`index.ts:514-561`).
///
/// `add` writes (creating parents), `delete` removes, `update` reads + derives
/// then either writes in place or writes the move target and removes the
/// original. Returns the [`AffectedPaths`].
pub async fn apply_hunks_to_files(
    hunks: &[Hunk],
    base_dir: &Path,
) -> Result<AffectedPaths, PatchError> {
    if hunks.is_empty() {
        return Err(PatchError::Apply("No files were modified.".to_string()));
    }

    let mut affected = AffectedPaths::default();

    for hunk in hunks {
        match hunk {
            Hunk::Add { path, contents } => {
                let target = resolve(base_dir, path);
                write_with_dirs(&target, contents).await?;
                affected.added.push(path.clone());
            }
            Hunk::Delete { path } => {
                let target = resolve(base_dir, path);
                tokio::fs::remove_file(&target)
                    .await
                    .map_err(|e| PatchError::Io(e.to_string()))?;
                affected.deleted.push(path.clone());
            }
            Hunk::Update {
                path,
                move_path,
                chunks,
            } => {
                let target = resolve(base_dir, path);
                let original = tokio::fs::read_to_string(&target)
                    .await
                    .map_err(|e| PatchError::Io(e.to_string()))?;
                let update = derive_new_contents_from_chunks(path, chunks, &original)?;
                let content = bom_join(&update.content, update.bom);
                if let Some(mv) = move_path {
                    let move_target = resolve(base_dir, mv);
                    write_with_dirs(&move_target, &content).await?;
                    tokio::fs::remove_file(&target)
                        .await
                        .map_err(|e| PatchError::Io(e.to_string()))?;
                    affected.modified.push(mv.clone());
                } else {
                    write_with_dirs(&target, &content).await?;
                    affected.modified.push(path.clone());
                }
            }
        }
    }

    Ok(affected)
}

async fn write_with_dirs(path: &Path, content: &str) -> Result<(), PatchError> {
    if let Some(parent) = path.parent() {
        tokio::fs::create_dir_all(parent)
            .await
            .map_err(|e| PatchError::Io(e.to_string()))?;
    }
    tokio::fs::write(path, content)
        .await
        .map_err(|e| PatchError::Io(e.to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn missing_markers_errors() {
        let err = parse_patch("just some text").unwrap_err();
        assert!(matches!(err, PatchError::MissingMarkers));
        assert_eq!(
            err.to_string(),
            "Invalid patch format: missing Begin/End markers"
        );
    }

    #[test]
    fn parse_add_file() {
        let patch =
            "*** Begin Patch\n*** Add File: hello.txt\n+Hello world\n+Second line\n*** End Patch";
        let hunks = parse_patch(patch).unwrap();
        assert_eq!(
            hunks,
            vec![Hunk::Add {
                path: "hello.txt".to_string(),
                contents: "Hello world\nSecond line".to_string(),
            }]
        );
    }

    #[test]
    fn parse_delete_file() {
        let patch = "*** Begin Patch\n*** Delete File: obsolete.txt\n*** End Patch";
        let hunks = parse_patch(patch).unwrap();
        assert_eq!(
            hunks,
            vec![Hunk::Delete {
                path: "obsolete.txt".to_string()
            }]
        );
    }

    #[test]
    fn parse_update_with_context_and_move() {
        let patch = "*** Begin Patch\n*** Update File: src/app.py\n*** Move to: src/main.py\n@@ def greet():\n-print(\"Hi\")\n+print(\"Hello\")\n*** End Patch";
        let hunks = parse_patch(patch).unwrap();
        assert_eq!(
            hunks,
            vec![Hunk::Update {
                path: "src/app.py".to_string(),
                move_path: Some("src/main.py".to_string()),
                chunks: vec![UpdateFileChunk {
                    old_lines: vec!["print(\"Hi\")".to_string()],
                    new_lines: vec!["print(\"Hello\")".to_string()],
                    change_context: Some("def greet():".to_string()),
                    is_end_of_file: false,
                }],
            }]
        );
    }

    #[test]
    fn parse_end_of_file_anchor() {
        let patch = "*** Begin Patch\n*** Update File: a.txt\n@@\n-old\n+new\n*** End of File\n*** End Patch";
        let hunks = parse_patch(patch).unwrap();
        let Hunk::Update { chunks, .. } = &hunks[0] else {
            panic!("expected update");
        };
        assert!(chunks[0].is_end_of_file);
    }

    #[test]
    fn heredoc_unwrap() {
        let patch = "cat <<'EOF'\n*** Begin Patch\n*** Delete File: x.txt\n*** End Patch\nEOF";
        let hunks = parse_patch(patch).unwrap();
        assert_eq!(
            hunks,
            vec![Hunk::Delete {
                path: "x.txt".to_string()
            }]
        );
    }

    #[test]
    fn derive_simple_update() {
        let chunks = vec![UpdateFileChunk {
            old_lines: vec!["b".to_string()],
            new_lines: vec!["B".to_string()],
            change_context: None,
            is_end_of_file: false,
        }];
        let update = derive_new_contents_from_chunks("f", &chunks, "a\nb\nc\n").unwrap();
        assert_eq!(update.content, "a\nB\nc\n");
        assert!(!update.unified_diff.is_empty());
        assert!(!update.bom);
    }

    #[test]
    fn seek_sequence_rstrip_pass() {
        let lines = vec!["foo   ".to_string(), "bar".to_string()];
        let pat = vec!["foo".to_string()];
        assert_eq!(seek_sequence(&lines, &pat, 0, false), Some(0));
    }

    #[test]
    fn seek_sequence_trim_pass() {
        let lines = vec!["   foo   ".to_string()];
        let pat = vec!["foo".to_string()];
        assert_eq!(seek_sequence(&lines, &pat, 0, false), Some(0));
    }

    #[test]
    fn seek_sequence_unicode_pass() {
        // Smart quote in the file, ASCII quote in the pattern.
        let lines = vec!["say \u{201C}hi\u{201D}".to_string()];
        let pat = vec!["say \"hi\"".to_string()];
        assert_eq!(seek_sequence(&lines, &pat, 0, false), Some(0));
    }

    #[test]
    fn eof_anchor_matches_from_end() {
        let lines = vec!["x".to_string(), "x".to_string(), "tail".to_string()];
        let pat = vec!["tail".to_string()];
        assert_eq!(seek_sequence(&lines, &pat, 0, true), Some(2));
    }

    #[test]
    fn derive_pure_addition_before_trailing_empty() {
        let chunks = vec![UpdateFileChunk {
            old_lines: vec![],
            new_lines: vec!["added".to_string()],
            change_context: None,
            is_end_of_file: false,
        }];
        let update = derive_new_contents_from_chunks("f", &chunks, "a\n").unwrap();
        assert_eq!(update.content, "a\nadded\n");
    }

    #[tokio::test]
    async fn apply_add_update_delete_move() {
        let dir = tempfile::tempdir().unwrap();
        let base = dir.path();
        tokio::fs::write(base.join("update.txt"), "a\nb\nc\n")
            .await
            .unwrap();
        tokio::fs::write(base.join("gone.txt"), "bye\n")
            .await
            .unwrap();
        tokio::fs::write(base.join("moved.txt"), "keep\nold\n")
            .await
            .unwrap();

        let hunks = vec![
            Hunk::Add {
                path: "new/created.txt".to_string(),
                contents: "fresh".to_string(),
            },
            Hunk::Delete {
                path: "gone.txt".to_string(),
            },
            Hunk::Update {
                path: "update.txt".to_string(),
                move_path: None,
                chunks: vec![UpdateFileChunk {
                    old_lines: vec!["b".to_string()],
                    new_lines: vec!["B".to_string()],
                    change_context: None,
                    is_end_of_file: false,
                }],
            },
            Hunk::Update {
                path: "moved.txt".to_string(),
                move_path: Some("dest.txt".to_string()),
                chunks: vec![UpdateFileChunk {
                    old_lines: vec!["old".to_string()],
                    new_lines: vec!["new".to_string()],
                    change_context: None,
                    is_end_of_file: false,
                }],
            },
        ];

        let affected = apply_hunks_to_files(&hunks, base).await.unwrap();
        assert_eq!(affected.added, vec!["new/created.txt".to_string()]);
        assert_eq!(affected.deleted, vec!["gone.txt".to_string()]);
        assert_eq!(
            affected.modified,
            vec!["update.txt".to_string(), "dest.txt".to_string()]
        );

        assert_eq!(
            tokio::fs::read_to_string(base.join("new/created.txt"))
                .await
                .unwrap(),
            "fresh"
        );
        assert!(!base.join("gone.txt").exists());
        assert_eq!(
            tokio::fs::read_to_string(base.join("update.txt"))
                .await
                .unwrap(),
            "a\nB\nc\n"
        );
        assert!(!base.join("moved.txt").exists());
        assert_eq!(
            tokio::fs::read_to_string(base.join("dest.txt"))
                .await
                .unwrap(),
            "keep\nnew\n"
        );
    }

    #[test]
    fn bom_roundtrip() {
        let with_bom = format!("{BOM}hello");
        let (b, text) = bom_split(&with_bom);
        assert!(b);
        assert_eq!(text, "hello");
        assert_eq!(bom_join("hello", true), with_bom);
        assert_eq!(bom_join("hello", false), "hello");
    }
}
